version: "3.4"

services:
  drill-and-practice:
    #container_name: app-p2-test
    build: drill-and-practice
    image: drill-and-practice
    restart: "no"
    volumes:
      - ./drill-and-practice/:/app
    ports:
      - 7777:7777
    depends_on:
      - database-test
      - flyway
    env_file:
      - ./drill-and-practice/config/test.env
  
  database-test:
    container_name: database-p2-test-8148f552-a160-4410-af87-07d05afc01dd
    image: postgres:14.1
    restart: "no"
    env_file:
        - ./drill-and-practice/config/test.env

  flyway:
    #container_name: flyway-p2-test
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database-test
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - ./drill-and-practice/config/test.env

  e2e-playwright: 
    entrypoint: "/bin/true"
    container_name: playwright-test
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - drill-and-practice
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests